### ISSUE TITLE
add support for raven-go

### ISSUE THREAD

**Issue by acirtautas** [willkg/kent#15]
Kent server stores data from golang sentry integration as bytes, and is not able to render error list nor error details.

```
User-Agent: raven-go/1.0
Content-Length: 1872
Content-Type: application/octet-stream
X-Sentry-Auth: Sentry sentry_version=4, sentry_key=public
Accept-Encoding: gzip
```

**Comment by willkg** [comment]
I was adding support for the raven-python client to fix an issue I had last week. I haven't tested Kent with Go, but it might fix the issue you're hitting, too.

I did a 0.4.0 release just now. Can you try that and see if that fixes it?

**Comment by acirtautas** [comment]
Thanks, that was really fast response, 

I have just tested the latest 0.4.0 version.

This time is does not crash, but message body is not decoded properly:
```json
{
    "error_id":"2b3c7cf6-b12d-4b90-bd9f-580da037d54f",
    "payload":{
        "error":"Kent could not decode body; see logs"
    },
    "project_id":1
}
```


I am not a python dev, but logs say: **exception when JSON-decoding body**
So looks like it was expect a string but got a binary data.


Though I have successfully decoded the payload with PHP/Symfony
```php
#[Route('/api/{project}/store/', name: 'store', methods:['POST'])]
public function store($project, Request $request): Response
{
    $payload = json_decode(zlib_decode(base64_decode($request->getContent())));

    // ...
    
    return $this->json(['success' => true]);
}
```

**Comment by willkg** [comment]
The Go support page on the Sentry site (https://docs.sentry.io/platforms/go/) walks through using their `sentry-go` library. When I build the example, it works fine with Kent and spits out these headers:

```
Host: localhost:5000
User-Agent: sentry-go/0.12.0
Content-Length: 530
Content-Type: application/json
X-Sentry-Auth: Sentry sentry_version=7, sentry_timestamp=1644251278, sentry_client=sentry.go/0.12.0, sentry_key=public
Accept-Encoding: gzip
```

The headers you have in the first comment suggest you're using a different library. Is that library supported? If so, where can I find documentation on it?

**Comment by willkg** [comment]
I adjusted the summary. I'm not going to add support for raven-go, but I'd accept a PR from someone.
