### ISSUE TITLE
Provide official docker image

### ISSUE THREAD

**Issue by michaelzangl** [willkg/kent#19]
It would be great if you could provide a ready to use docker image, it would make integrating this in CI much easier ;-)

**Comment by willkg** [comment]
Glad this is helping you!

I've got a `Dockerfile` you can use--it's what I use. I don't plan on providing a Docker image at this time. Sorry!

**Comment by yoobles** [comment]
Would you be willing to reconsider this? It's fairly simple to setup Github Actions so that a Docker image that will be pushed on release. 

Currently I am using kent from a fork along with a self hosted Docker image: 

```docker
FROM python:3.10.1-alpine3.15

WORKDIR /app/

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN pip install 'kent==0.4.0'

USER guest
EXPOSE 3000

ENTRYPOINT ["/usr/local/bin/kent-server"]
CMD ["run", "--host", "0.0.0.0", "--port", "3000"]
```

**Comment by willkg** [comment]
I don't plan on providing and maintaining a Docker image at this time.
