### ISSUE TITLE
Misleading server output wrt. bind address

### ISSUE THREAD

**Issue by dimaqq** [willkg/kent#39]
The Dockerfile in this project and the hack to always listen on localhost (ipv4 or ipv6) leads to a situation where the port in the container is not reachable from other containers or host.

Instead, kent should bind to `::` or `0.0.0.0`

This cannot be worked around with:

`docker run -p 5000:5000 --entrypoint "" quay.io/dimaqq/kent flask --app kent.app run --host ::`

Or in docker-compose.yaml:

```yaml
version: "3.4"
services:
  sentry:
    image: quay.io/dimaqq/kent:latest
    ports:
      - "5000:5000"
    entrypoint: ""
    command: "flask --app kent.app run --host ::"
```

Because the Python code in kent specifically overrides the bind address with `::1` or `127.0.0.1` 😭 

```
> docker compose run sentry
 * Serving Flask app 'kent.app'
 * Debug mode: off
[2022-11-18 09:01:51,484] INFO: _internal: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (::)
 * Running on http://[::1]:5000
 * Running on http://[::1]:5000
```

And thus the app is accessible from inside the container but not from outside the container.

**Comment by willkg** [comment]
Can you do a PR?

**Comment by willkg** [comment]
I think `get_interface_ip` is only used for getting the thing to display to the user. It's not used for determining the thing to actually bind to.

https://github.com/pallets/werkzeug/blob/main/src/werkzeug/serving.py#L798-L803

If you're not able to access Kent from outside the container, then maybe there's something else going on?

**Comment by willkg** [comment]
Your example has you running Kent using `flask --app`. What happens when you use the `kent-server` cli as documented in the README?

**Comment by dimaqq** [comment]
it's the same when running as `kent-server`

#40 is a simple change that fixes the issue, but I'm not sure if that's the correct fix.

**Comment by willkg** [comment]
I don't see how #40 fixes the issue. Here's the docstring for get_interface_ip:

https://github.com/pallets/werkzeug/blob/3115aa6a6276939f5fd6efa46282e0256ff21f1a/src/werkzeug/serving.py#L633

It's _only_ used for displaying text to the user. It's not used for determining what to bind to.

It's Monday, so maybe I'm just slow. Can you walk me through your theory with steps to reproduce?

**Comment by dimaqq** [comment]
Maybe I was a confused too. Let me pull the earlier docker image to check this.

**Comment by dimaqq** [comment]
Ahh you are correct... I was mislead by container output (build from main branch):

```command
> docker run -p 5000:5000 quay.io/dimaqq/kent:2022-11-18 run --host ::
 * Serving Flask app 'kent.app'
 * Debug mode: off
[2022-11-21 23:14:16,782] INFO: _internal: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (::)
 * Running on http://[::1]:5000
 * Running on http://[::1]:5000
[2022-11-21 23:14:16,782] INFO: _internal: Press CTRL+C to quit
```

The process did in fact bind to `::`
But the output stated `::1` and I believed that

Let me rename the issue.

**Comment by dimaqq** [comment]
or maybe I can just close, because there's an extra line `Running on all addresses (::)` so I guess it works as intended?

**Comment by willkg** [comment]
We could keep this open. The output is awkward and I wish it were more helpful. I tinkered with it for a while which got me to monkeypatching the `get_interface_ip` function, but it's still awkward and I gave up after that. It's probably the case that I'm trying to use werkzeug because it's convenient, but I'm using it in a way it's really not meant for and I should be using a different wsgi server.
