### ISSUE TITLE
Support the envelope API

### ISSUE THREAD

**Issue by pjenvey** [willkg/kent#42]
Sentry added a new API for submitting events: [via envelopes](https://develop.sentry.dev/sdk/envelopes/).

I know the latest rust sentry client lib uses envelopes instead of the [store endpoint](https://develop.sentry.dev/sdk/store/) so it would be nice if kent also supported it.

Here's a little basic example of how we switched an integration test from the store to the envelope api: [
tests/test_integration_all_rust.py change](https://github.com/mozilla-services/autopush-rs/commit/008e3e8c400d85ab7b863e96d8d12a849733c8e9#diff-8162445da58c674055187c7926988ec44c6715529d4db774ccf1fe6424ea1329)

**Comment by willkg** [comment]
In November, in #18, I determined that the envelope API requires Relay and that was outside the scope of Kent. The docs you mention have this at the top:

> Envelopes require Relay, which has been introduced in Sentry v20.6.0. Earlier versions of Sentry do not support Envelopes and respond with HTTP error 404 Not Found to envelope uploads. Likewise, Relay requires support for Envelopes on the upstream and cannot be used with older versions of Sentry.

Do you think I got that wrong or that something changed since then?

**Comment by pjenvey** [comment]
I'm not sure they mean Relay is mandatory as of v20.6.0 -- however `Likewise, Relay requires support for Envelopes on the upstream and cannot be used with older versions of Sentry` suggests upstream Sentry also supports this envelope API.

This is a bit confusing but the upstream support makes sense because not only does the Rust client lib now solely use the envelope API but so do the [Ruby](https://github.com/getsentry/sentry-ruby) and [native](https://github.com/getsentry/sentry-native) versions -- they state in their README's they require a minimum of v20.6.0 because of this. See [sentry-ruby switching to envelopes](https://github.com/getsentry/sentry-ruby/issues/1062) and [native adjusting their docs accordingly](https://github.com/getsentry/sentry-native/pull/404).

So maybe they mean the endpoint was "introduced by relay" but if Relay isn't required, Sentry itself must also support it and thus some of the SDKs have switched over to it entirely.

**Comment by willkg** [comment]
Their docs could be out of date, too. I know I've found other parts of their docs out of date before.

I'm not sure what we'd want in an implementation. The payload is a bunch of JSON objects. We want to be able to retrieve the Sentry event via the Kent API to compare it with what we expected to send, so the closer it is to the original payload, the better. Maybe we keep the original payload and a decoded version so we can extract data from it for summaries and such?

It's probably helpful to add another metadata item regarding how the Sentry event was submitted in the error metadata here:

https://github.com/willkg/kent/blob/c29cad2f0bb6ea6bc366d2966b86de4b644ca298/src/kent/app.py#L45

https://github.com/willkg/kent/blob/c29cad2f0bb6ea6bc366d2966b86de4b644ca298/src/kent/app.py#L66

I'm not sure what other things we'd want to think about here.

I'm not going to get to implementing this any time soon. I'd definitely take a PR if someone has time to work on it.
