### ISSUE TITLE
[Feature request] Support Security Policy Reporting endpoint

### ISSUE THREAD

**Issue by stevejalim** [willkg/kent#59]
Sentry is now supporting a few [security policy reporting options](https://docs.sentry.io/product/security-policy-reporting/), including CSP.

Those reports go to a distinct route `/api/:some_id/security/` and currently `kent-server` doesn't consume those reports happily. 

For example, with a localhost page and a CSP featuring `report-uri http://public@127.0.0.1:8012/1`, if there's a violation `kent-server` just responds with a 404:

```
[2023-11-06 13:02:54,328] INFO: _internal: 127.0.0.1 - - [06/Nov/2023 13:02:54] "POST /1 HTTP/1.1" 404 -
``` 

Which is fair enough - it's just a route that's not supported yet

To help avoid slamming a production/paid-for Sentry profile during development and integration testing, it would be nice to be able to use this locally. 

I'd be open to contributing some code for this, but it'd be a bit of a way down my work backlog, so if anyone else fancies picking this up sooner, that'd be really handy 💯

**Comment by willkg** [comment]
I'm a little confused about this. Is the `report-uri` set correctly in the example? Seems like it's not if the url scheme is `/api/:project_id/security/` . Or is it the case that Sentry handles CSP reports to `/:project_id` as well and Kent should, too?

**Comment by willkg** [comment]
That makes sense! Thank you!

I don't know when I'll get to this. Among other things, this is not a feature I'm using, so I'd have to figure out how to set up a test to see what's going on.

Adding support for new APIs should be pretty straight forward depending on what's in the payload. You'd probably want to add something like this:

https://github.com/willkg/kent/blob/600d1995a55075c14faeff3a230eb3ce764a4f39/src/kent/app.py#L172-L224

Then maybe we adjust the payload to fit in `Error` or maybe we extend Kent to have a different data structure for security reports.

**Comment by stevejalim** [comment]
Cheers Will! I'm happy to take a good swing at it, but it'll be low down on my list for now.

> Then maybe we adjust the payload to fit in Error or maybe we extend Kent to have a different data structure for security reports.

Yeah I think we should just park it all in `Error` - that's similar to what happens in real Sentry, at least for initial support - and then we see how we go

**Comment by stevejalim** [comment]
Feel free to assign this to me, to help me remember to come back to it when I have time

**Comment by willkg** [comment]
@stevejalim I think I got this right. The change is landed in main now. Does this work for the CSP reporting that you're working on? If so, can you copy/paste an example payload?

**Comment by stevejalim** [comment]
Here you go! Minorly redacted example of a `frame-src` violation

```{"error_id":"b241d960-c971-45ea-aeda-43ea1597366c","payload":{"csp-report":{"blocked-uri":"https://www.youtube.com","disposition":"enforce","document-uri":"http://localhost:8000/test-page/","effective-directive":"frame-src","original-policy":"style-src 'self' 'unsafe-inline'; base-uri 'none'; media-src 'self'; object-src 'none'; child-src 'self'; img-src 'self' data: https://storage.example.com/bucket-name-here/ https://region1.google-analytics.com; font-src 'self'; default-src 'self'; connect-src 'self' https://region1.google-analytics.com https://basket.mozilla.org; script-src 'self' http://www.googletagmanager.com; frame-src 'self'; report-uri http://public@127.0.0.1:8015/api/1/security/","referrer":"","status-code":0,"violated-directive":"frame-src"}},"project_id":1}
```

**Comment by willkg** [comment]
Formatting that so it's a little more readable:

```json
{
  "error_id":"b241d960-c971-45ea-aeda-43ea1597366c",
  "payload":{
    "csp-report":{
      "blocked-uri":"https://www.youtube.com",
      "disposition":"enforce",
      "document-uri":"http://localhost:8000/test-page/",
      "effective-directive":"frame-src",
      "original-policy":"style-src 'self' 'unsafe-inline'; base-uri 'none'; media-src 'self'; object-src 'none'; child-src 'self'; img-src 'self' data: https://storage.example.com/bucket-name-here/ https://region1.google-analytics.com; font-src 'self'; default-src 'self'; connect-src 'self' https://region1.google-analytics.com https://basket.mozilla.org; script-src 'self' http://www.googletagmanager.com; frame-src 'self'; report-uri http://public@127.0.0.1:8015/api/1/security/",
      "referrer":"",
      "status-code":0,
      "violated-directive":"frame-src"
    }
  },
  "project_id":1
}
```

Huh. That's a really different shape than what I was expecting. I read this article:

https://notificare.com/blog/2022/03/18/Monitoring-Content-Security/

It calls this the "older browser" format. I'll fix the summary handling to support both.

Thank you!

**Comment by willkg** [comment]
With that last fix, I think we're good here. Closing this out.
